<a href="https://colab.research.google.com/github/Ankush1oo8/Data_Analyst/blob/main/data_Analysis/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is NumPy?

NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides:

Powerful N-dimensional arrays: These are efficient data structures for storing and manipulating large datasets, especially numerical data.
Broadcasting: This mechanism allows you to perform operations on arrays of different shapes in a concise and efficient manner.

Mathematical functions: NumPy has a wide range of built-in functions for linear algebra, Fourier transforms, random number generation, and more, optimized for performance.
Tools for integrating C/C++ and Fortran code: This allows for even greater performance optimization.

How to Use NumPy in Google Colab

In [ ]:
import numpy as np

(The np alias is a common convention)

In [ ]:
#create array using numpy
#1D array
arr1=np.array([1,2,3])
print(arr1)
arr1.shape

[1 2 3]


(3,)

In [ ]:
arr2=np.array([[1,2,3],[5,6,7]])
print(arr2)
arr2.shape

[[1 2 3]
 [5 6 7]]


(2, 3)

In [ ]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [ ]:
np.arange(0,10,1).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr2.size

6

In [ ]:
arr2.itemsize

8

In [ ]:
# numpy vectorize array operation
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print("Addition",arr1+arr2)
print("Subtraction",arr1-arr2)
print("Multiplication",arr1*arr2)
print("Division",arr1/arr2)

Addition [5 7 9]
Subtraction [-3 -3 -3]
Multiplication [ 4 10 18]
Division [0.25 0.4  0.5 ]


In [ ]:
## universal functions
arr=np.array([1,2,3])
np.sqrt(arr)

## exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

##natural log
print(np.log(arr))

[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]


In [ ]:
## array slicing and indexing

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr[0][0])

1


In [ ]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[1:
    ,2:]

array([[6],
       [9]])

In [ ]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
## modifying element

arr[0][0]=100

In [ ]:
print(arr)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
### statistical concept - normalization
## to have mean of 0 and std deviation

data=np.array([10,1,2,3,4,5,6,8,8,9,7,5,4,3,2])

#mean
mean=np.mean(data)
print("Mean: ",mean)

#median
median=np.median(data)
print("Median: ",median)

#standard deviation
std_dev=np.std(data)
print("Standard Deviation: ",std_dev)

#variance
variance=np.var(data)
print("Variance: ",variance)

Mean:  5.133333333333334
Median:  5.0
Standard Deviation:  2.679966832298904
Variance:  7.182222222222222


In [ ]:
# logical operation
data[(data>5) & (data<8)]


array([6, 7])